### ISSUE TITLE
Share pretrained models via an alternative cloud service 

### ISSUE THREAD

**Issue by GenkiK** [XiaobenLi00/U-HMR#2]
Thank you for your great work!

Could you share the pretrained models other than Baidu?

Thanks

**Comment by MakingBigNewsWallace** [comment]
Yes, downloading from Baidu was too slow and it takes days to finish. I also wonder if the authors could provide a google drive link, many thanks!

**Comment by XiaobenLi00** [comment]
Thanks a lot for following our work!

Considering the storage limitations of Google Drive, I choose use [OneDrive](https://1drv.ms/f/s!AqnMGeLS2QFOhbpt34u-GTmwNIpbRQ?e=aSWriS) to share data.

Please be free to download and conact me if you still have problems or questions!

Best, 
Xiaoben

**Comment by XiaobenLi00** [comment]
Closing this issue, if you still have problems with downloading, please free feel to contact me.
